apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-react-app-depl
spec: 
  selector: 
    matchLabels: 
     app: react-app
  replicas: 2
  template: 
    metadata: 
     labels:
      app: react-app
    spec: 
      containers:
        - name: react-app
          image: ayushthakur/my-react-app:latest
---
apiVersion: v1
kind: Service
metadata: 
  name: my-react-app-srv
spec: 
  type: NodePort
  selector: 
    app: react-app
  ports: 
   - name: my-port
     port: 3000
     targetPort: 3000
